version: "3.9"
name: redis

services:      
    redis:
        extends:
            file: redis/redis.yml
            service: redis
            
    broker-kafka-0:
        depends_on:
            - redis
        extends:
            file: ui/ui.yml
            service: redis-ui