version: '3.9'

services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379