version: '3.9'

services:
  zookeeper:
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    hostname: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2182:2182
      - 2183:2183