version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:${RABBIT_VERSION}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"