version: '3.9'
services:
  broker-kafka-0:
    image: bitnami/kafka:latest
    hostname: broker-kafka-0
    restart: on-failure:2
    environment:      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_LISTENERS: INTERNAL://broker-kafka-0:19091,EXTERNAL://broker-kafka-0:9091
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-kafka-0:19091,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3      
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - 9091:9091
      
  broker-kafka-1:
    image: bitnami/kafka:latest
    hostname: broker-kafka-1
    restart: on-failure:2
    environment:      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_LISTENERS: INTERNAL://broker-kafka-1:19092,EXTERNAL://broker-kafka-1:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-kafka-1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092     
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3      
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - 9092:9092

  broker-kafka-2:
    image: bitnami/kafka:latest
    hostname: broker-kafka-2
    restart: on-failure:2
    environment:      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_LISTENERS: INTERNAL://broker-kafka-2:19093,EXTERNAL://broker-kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-kafka-2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093   
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3      
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - 9093:9093