version: "3.9"

services:
  nexus:
    image: sonatype/nexus3:${NEXUS_VERSION}
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    environment:
      NEXUS_CONTEXT: nexus
    ports:
      - ${REDIS_PORT}:8081

volumes:
  nexus-data:
    driver: local