version: '3.9'

services:
  redis-insight:
    image: redis/redisinsight:${REDIS_INSIGHT_VERSION}
    container_name: redis-insight
    hostname: redis-insight
    ports:
      - ${REDIS_INSIGHT_PORT}:5540